#Credentials 

AWS_ACCESS_KEY_ID: 
AWS_SECRET_ACCESS_KEY: 
development:
	SENDGRID_USERNAME: 
	SENDGRID_PASSWORD: 
	AWS_BUCKET: 
  FACEBOOK_SECRET:
  FACEBOOK_ID: 
production:
	AWS_BUCKET: 
  FACEBOOK_SECRET:
  FACEBOOK_ID: 